version: '3.4'

services:
  kwetter_user:
    image: ${DOCKER_REGISTRY-}kwetteruser
    build:
      context: .
      dockerfile: Kwetter_User/Dockerfile
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: kwetter
      MYSQL_USER: kwetter
      MYSQL_PASSWORD: password
