apiVersion: apps/v1
kind: Deployment
metadata:
  name: kwetter-user-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: kwetter-user
  template:
    metadata:
      labels:
        app: kwetter-user
    spec:
      containers:
      - name: kwetter-user
        image: yannickrosheuvel/kwetteruser:latest
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_USER
          value: kwetter
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: kwetter
      restartPolicy: Always
