apiVersion: v1
kind: Service
metadata:
  name: kwetter-user-service-better
  labels:
    app: kwetter-user
    service: kwetter-user-service-better
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: kwetteruserservice
    name: kwetteruserservice
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: kwetter-user-service-better
