apiVersion: v1
kind: Service
metadata:
  name: kwetter-user-service
  labels:
    app: kwetter-user
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: kwetter-user